version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-motd-bot
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml:ro
      - meme-data:/app/memes

volumes:
  meme-data:
    driver: local